#!/bin/sh

usage() {
  echo "Usage: $0 <file_or_directory>"
  exit 1
}

[ -z "$1" ] && usage

commands_exist() {
  rc=0
  for cmd in "$@"; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
      rc=1
      break
    fi
  done
  return $rc
}

mime=$(file -bL --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}

if [ -d "$1" ]; then
  if commands_exist lsd; then
    lsd --git -hl --color=always "$1"
  else
    ls -la "$1"
  fi
elif [ "$category" = image ]; then
  if commands_exist chafa; then
    chafa "$1"
  fi
  if commands_exist exiftool; then
    exiftool "$1"
  fi
elif [ "$kind" = vnd.openxmlformats-officedocument.spreadsheetml.sheet ] ||
  [ "$kind" = vnd.ms-excel ]; then
  if commands_exist in2csv xsv bat; then
    in2csv "$1" | xsv table | bat -ltsv --color=always
  fi
elif [ "$category" = text ]; then
  if commands_exist bat; then
    bat --color=always "$1"
  else
    cat "$1"
  fi
fi
