---
git:
  paging:
    colorArg: always
    pager: >-
      delta --features=mantis-shrimp --paging=never --line-numbers --hyperlinks \
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
