#   ───────────────────────────────── Git ───────────────────────────────

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"

[plugin]
prepend_previewers = [
  #   ──────────────────────────────── Piper ──────────────────────────────
  { url = "*/", run = 'piper -- lsd -v --tree --depth 4 --color=always --icon=always --group-dirs first "$1"' },
  #   ──────────────────────────────── DuckDB ────────────────────────────────
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.json", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.txt", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
]

prepend_preloaders = [
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.json", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.txt", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false },
]
