#!/usr/bin/env zsh

#          ╭──────────────────────────────────────────────────────────╮
#          │                     ZPROFILE DARWIN                      │
#          ╰──────────────────────────────────────────────────────────╯

#   ───────────────────────── Restore .zshenv PATH ─────────────────────────

# Necessary on macOS due to Apple path_helper path manipulation
if [[ -n ${ORIGINAL_PATH-} && $PATH != "$ORIGINAL_PATH" ]]; then
  PATH=$ORIGINAL_PATH:$PATH
  typeset -U path
fi

unset ORIGINAL_PATH
