#!/usr/bin/env zsh

#          ╭──────────────────────────────────────────────────────────╮
#          │                      ZSHENV DARWIN                       │
#          ╰──────────────────────────────────────────────────────────╯

#   ──────────────────── XDG Runtime Dir Specification ──────────────────

export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}/$(id -u)-runtime-dir}

if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
  mkdir -p -- "$XDG_RUNTIME_DIR" && chmod 700 "$XDG_RUNTIME_DIR"
fi

#   ─────────────────────────── Helper Functions ───────────────────────────

path_append() {
  local var_name=$1
  local dir=$2
  if [[ -d "$dir" ]]; then
    if [[ -z "${(P)var_name}" ]]; then
      export $var_name="$dir"
    else
      export $var_name="${(P)var_name}:$dir"
    fi
  fi
}

#   ─────────────────────────── System Man Path ─────────────────────────

path_append MANPATH "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/\
usr/share/man"

#   ─────────────────────────────── OrbStack ───────────────────────────────

if [[ -f "$HOME/.orbstack/shell/init.zsh" ]]; then
  source "$HOME/.orbstack/shell/init.zsh" 2>/dev/null || :
fi

#   ────────────────────────────── Puppeteer ────────────────────────────

# Currently needed for Mermaid to work
export PUPPETEER_EXECUTABLE_PATH=\
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
