#!/usr/bin/env zsh

#          ╭──────────────────────────────────────────────────────────╮
#          │                       ZSHRC DARWIN                       │
#          ╰──────────────────────────────────────────────────────────╯

#   ──────────────────────────────── Nix ─────────────────────────────────

[[ -d /run/current-system/sw/share/zsh/site-functions ]] &&
  fpath+=("/run/current-system/sw/share/zsh/site-functions")

#   ────────────────────────────── Oh-My-Zsh ────────────────────────────

plugins+=(
  1password
)
