#!/usr/bin/env zsh

#######################################################################
#                              Oh-My-Zsh                              #
#######################################################################

export ZSH="$ZDOTDIR/oh-my-zsh"
export ZSH_THEME="powerlevel10k/powerlevel10k"

#############
#  FZF-Tab  #
#############

plugins+=(fzf-tab)

# Use default instead
# zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will
# ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the
# unambiguous prefix
zstyle ':completion:*' menu no
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
zstyle ':fzf-tab:*' fzf-flags --bind=tab:accept
# To make fzf-tab follow FZF_DEFAULT_OPTS.
# NOTE: This may lead to unexpected behavior since some flags break this plugin.
# See Aloxaf/fzf-tab#455.
# zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' popup-min-size 240 60

zstyle ':fzf-tab:complete:*' fzf-preview \
  '[[ -d $realpath ]] && lsd -1 --color=always --icon=always $realpath || \
  bat -n --color=always --line-range :10000 $realpath'

zstyle ':fzf-tab:complete:*:(options|argument-1)' fzf-preview
zstyle ':fzf-tab:*' continuous-trigger '/'

zstyle ':fzf-tab:complete:*:*' fzf-preview 'less ${(Q)realpath}'

# give a preview of commandline arguments when completing `kill`
zstyle ':completion:*:*:*:*:processes' command \
  "ps -u $USER -o pid,user,comm -w -w"
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-preview \
  '[[ $group == "[process ID]" ]] && ps -p $word -o command= -w -w'
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-flags \
  --preview-window=down:3:wrap

zstyle ':fzf-tab:complete:(-command-|-parameter-|-brace-parameter-|printenv|export|unset|expand):*' \
	fzf-preview 'echo ${(P)word}'

# it is an example. you can change it
zstyle ':fzf-tab:complete:git-(add|diff|restore):*' fzf-preview \
	'git diff $word | delta'
zstyle ':fzf-tab:complete:git-log:*' fzf-preview \
	'git log --color=always $word'
zstyle ':fzf-tab:complete:git-help:*' fzf-preview \
	'git help $word | bat -plman --color=always'
zstyle ':fzf-tab:complete:git-show:*' fzf-preview \
	'case "$group" in
	"commit tag") git show --color=always $word ;;
	*) git show --color=always $word | delta ;;
	esac'
zstyle ':fzf-tab:complete:git-checkout:*' fzf-preview \
	'case "$group" in
	"modified file") git diff $word | delta ;;
	"recent commit object name") git show --color=always $word | delta ;;
	*) git log --color=always $word ;;
	esac'

zstyle ':fzf-tab:complete:brew-(install|uninstall|search|info):*-argument-rest' fzf-preview 'brew info $word'

zstyle ':fzf-tab:complete:tldr:argument-1' fzf-preview 'tldr --color $word'

zstyle ':fzf-tab:complete:-command-:*' fzf-preview \
  '(out=$(tldr --color "$word") 2>/dev/null && echo $out) || (out=$(MANWIDTH=$FZF_PREVIEW_COLUMNS man "$word") 2>/dev/null && echo $out) || (out=$(which "$word") && echo $out) || echo "${(P)word}"'

zstyle ':fzf-tab:complete:(\\|)run-help:*' fzf-preview 'run-help $word'
zstyle ':fzf-tab:complete:(\\|*/|)man:*' fzf-preview 'man $word'

#############
#  Plugins  #
#############

# In case we ever use zsh-syntax-highlighting again
# if [[ -f "$HOME/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh" ]];
# then
#   source "$HOME/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh"
# fi

plugins+=(
  alias-finder
  aliases
  bazel
  catimg
  colored-man-pages
  colorize
  command-not-found
  copybuffer
  copyfile
  copypath
  dbt
  dircycle
  dirhistory
  fast-syntax-highlighting
  fzf
  gcloud
  gh
  git
  git-prompt
  gitfast
  gnu-utils
  gpg-agent
  httpie
  jsontools
  pip
  pre-commit
  python
  rsync
  rust
  safe-paste
  ssh
  ssh-agent
  thefuck
  # tmux  # Interacts badly with "Oh my tmux!"
  vi-mode
  fancy-ctrl-z
  web-search
  zoxide
  # zsh-autocomplete  # Prefer without, but a matter of taste
  zsh-autosuggestions
  zsh-cargo-completion
  zsh-completions
  # zsh-syntax-highlighting  # Using fast-syntax-highlighting instead
)

#############
#  Vi Mode  #
#############

VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true

###############
#  SSH Agent  #
###############

zstyle :omz:plugins:ssh-agent agent-forwarding yes
zstyle :omz:plugins:ssh-agent quiet yes
zstyle :omz:plugins:ssh-agent lazy yes

COMPLETION_WAITING_DOTS="true"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ff00ff,bg=cyan,bold,underline"
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(brackets pattern cursor)

######################
#  Source Oh-My-Zsh  #
######################

source $ZSH/oh-my-zsh.sh
