#!/usr/bin/env zsh

#######################################################################
#                              ZPROFILE                               #
#######################################################################

if [[ -f "$HOME/.zsh/zprofile_$ZSH_UNAME" ]]; then
  source "$HOME/.zsh/zprofile_$ZSH_UNAME"
fi
